FROM postgres:alpine
LABEL name=weather_analyser_db:2

EXPOSE 5432

ENV POSTGRES_DB=weather_analyser
ENV POSTGRES_USER=weather_analyser_manager
ENV POSTGRES_PASSWORD=manager

COPY postgres.sql.ddl/init.sql /docker-entrypoint-initdb.d/

VOLUME /var/lib/postgresql/data