spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      min-idle: 3
      maximum-pool-size: 6
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

server:
  port: ${SERVER_PORT}

app:
  location: ${LOCATION}

scheduled:
  task:
    fixedRate: ${SCHEDULED_UPDATE}
